### PR TITLE
update rspotify crate to v0.12.0

### PR DESCRIPTION
**Pull request by SimonStjernholm**
| - | - |
| --- | --- |
| Issue | not related to any  |
| Dependencies |  none|
| Decisions | I've updated the cargo.lock file with `cargo update`, since manual docker builds currently  won't work with the main repository. |
| note: | I don't know if this is the correct procedure |

### CODE REVIEW

**Comment by joao-conde** [comment]
The point of Cargo.lock is to ensure the versions are the same so it should build for you anyways right?
Can you post the error log of your build step?

**Comment by SimonStjernholm** [comment]
```#15 [build 8/10] RUN cargo build --release --locked
#15 27.36 Compiling slab v0.4.7
#15 27.75 Compiling futures-channel v0.3.21
#15 28.10 Compiling futures-task v0.3.21
#15 29.75 Compiling ring v0.16.20
#15 30.83 Compiling tokio v1.20.1
#15 31.15 Compiling futures-util v0.3.21
#15 36.73 Compiling tokio-macros v1.8.0
#15 38.00 Compiling futures-macro v0.3.21
#15 39.46 Compiling mio v0.8.4
#15 39.61 Compiling signal-hook-registry v1.4.0
#15 40.85 Compiling num_cpus v1.13.1
#15 40.97 Compiling socket2 v0.4.4
#15 42.11 Compiling pin-utils v0.1.0
#15 42.14 Compiling futures-io v0.3.21
#15 48.27 Compiling untrusted v0.7.1
#15 48.37 Compiling spin v0.5.2
#15 54.77 Compiling openssl-sys v0.9.75
#15 55.40 Compiling getrandom v0.2.7
#15 55.66 Compiling num-traits v0.2.15
#15 55.86 Compiling fnv v1.0.7
#15 55.92 Compiling http v0.2.8
#15 60.82 Compiling tracing-attributes v0.1.22
#15 63.51 Compiling tracing-core v0.1.28
#15 65.13 Compiling unicase v2.6.0
#15 65.33 Compiling httparse v1.7.1
#15 65.45 Compiling tracing v0.1.35
#15 66.27 Compiling webpki v0.22.0
#15 67.37 Compiling indexmap v1.9.1
#15 67.49 Compiling rustls v0.20.6
#15 67.59 Compiling tinyvec_macros v0.1.0
#15 67.64 Compiling bitflags v1.3.2
#15 67.67 Compiling hashbrown v0.12.3
#15 67.69 Compiling tinyvec v1.6.0
#15 69.24 Compiling sct v0.7.0
#15 69.27 Compiling thiserror-impl v1.0.31
#15 69.55 Compiling foreign-types-shared v0.1.1
#15 69.59 Compiling percent-encoding v2.2.0
#15 69.88 Compiling openssl v0.10.41
#15 70.24 Compiling form_urlencoded v1.1.0
#15 70.58 Compiling foreign-types v0.3.2
#15 71.42 Compiling thiserror v1.0.31
#15 71.48 Compiling unicode-normalization v0.1.21
#15 73.66 Compiling tokio-util v0.7.3
#15 76.77 Compiling openssl-macros v0.1.0
#15 77.36 Compiling try-lock v0.2.3
#15 77.43 Compiling unicode-bidi v0.3.8
#15 79.40 Compiling native-tls v0.2.10
#15 79.62 Compiling ryu v1.0.10
#15 80.04 Compiling serde_json v1.0.82
#15 80.41 Compiling idna v0.3.0
#15 83.48 Compiling want v0.3.0
#15 94.27 Compiling h2 v0.3.13
#15 97.74 Compiling http-body v0.4.5
#15 98.03 Compiling rand_core v0.6.3
#15 98.37 Compiling crypto-common v0.1.6
#15 98.53 Compiling block-buffer v0.10.2
#15 98.65 Compiling lock_api v0.4.7
#15 98.86 Compiling base64 v0.13.0
#15 99.59 Compiling httpdate v1.0.2
#15 100.2 Compiling tower-service v0.3.2
#15 100.3 Compiling rustversion v1.0.8
#15 100.7 Compiling openssl-probe v0.1.5
#15 101.9 Compiling hyper v0.14.20
#15 115.0 Compiling digest v0.10.3
#15 115.2 Compiling mime_guess v2.0.4
#15 116.2 Compiling url v2.3.1
#15 121.3 Compiling tokio-rustls v0.23.4
#15 121.7 Compiling cpufeatures v0.2.2
#15 121.7 Compiling scopeguard v1.1.0
#15 121.8 Compiling encoding_rs v0.8.31
#15 123.2 Compiling tokio-native-tls v0.3.0
#15 123.4 Compiling webpki-roots v0.22.4
#15 123.5 Compiling mime v0.3.16
#15 123.6 Compiling ppv-lite86 v0.2.16
#15 124.2 Compiling either v1.7.0
#15 124.4 Compiling parking_lot_core v0.9.3
#15 124.4 Compiling async-trait v0.1.56
#15 124.7 Compiling lazy_static v1.4.0
#15 124.8 Compiling tokio-socks v0.5.1
#15 125.0 Compiling rand_chacha v0.3.1
#15 127.0 Compiling hyper-tls v0.5.0
#15 127.4 Compiling hyper-rustls v0.23.0
#15 127.7 Compiling rustls-pemfile v1.0.0
#15 128.6 Compiling serde_urlencoded v0.7.1
#15 129.0 Compiling cmake v0.1.48
#15 129.5 Compiling num-integer v0.1.45
#15 129.8 Compiling crc32fast v1.3.2
#15 130.1 Compiling ipnet v2.5.0
#15 132.2 Compiling smallvec v1.9.0
#15 133.0 Compiling reqwest v0.11.11
#15 136.6 Compiling audiopus_sys v0.2.2
#15 137.0 Compiling aho-corasick v0.7.18
#15 138.0 Compiling rand v0.8.5
#15 141.9 Compiling sha-1 v0.10.0
#15 142.4 Compiling futures-executor v0.3.21
#15 143.2 Compiling pin-project-internal v1.0.11
#15 145.5 Compiling utf-8 v0.7.6
#15 145.7 Compiling crossbeam-utils v0.8.11
#15 145.9 Compiling adler v1.0.2
#15 146.1 Compiling subtle v2.4.1
#15 146.2 Compiling regex-syntax v0.6.27
#15 150.3 Compiling byteorder v1.4.3
#15 150.7 Compiling heck v0.4.0
#15 150.9 Compiling strum_macros v0.24.2
#15 154.0 Compiling tungstenite v0.17.3
#15 161.3 Compiling regex v1.6.0
#15 165.0 Compiling universal-hash v0.4.1
#15 165.2 Compiling miniz_oxide v0.5.3
#15 168.1 Compiling pin-project v1.0.11
#15 168.1 Compiling futures v0.3.21
#15 185.9 Compiling num-traits v0.1.43
#15 186.0 Compiling ordered-float v2.10.0
#15 186.6 Compiling cipher v0.3.0
#15 187.0 Compiling time v0.1.44
#15 188.4 Compiling num_threads v0.1.6
#15 188.9 Compiling pnet_base v0.28.0
#15 188.9 Compiling rustc-serialize v0.3.24
#15 189.1 Compiling zeroize v1.3.0
#15 189.2 Compiling opaque-debug v0.3.0
#15 189.2 Compiling serenity v0.11.5
#15 189.2 error[E0310]: the parameter type `T` may not live long enough
#15 189.2 --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-serialize-0.3.24/src/serialize.rs:1155:5
#15 189.2 |
#15 189.3 1155 | fn decode(d: &mut D) -> Result, D::Error> {
#15 189.3 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#15 189.3 | |
#15 189.3 | the parameter type `T` must be valid for the static lifetime...
#15 189.3 | ...so that the type `T` will meet its required lifetime bounds...
#15 189.3 |
#15 189.3 note: ...that is required by this bound
#15 189.3 --> /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/borrow.rs:180:30
#15 189.3 help: consider adding an explicit lifetime bound
#15 189.3 |
#15 189.3 1151 | impl<'a, T: ?Sized + 'static> Decodable for Cow<'a, T>
#15 189.3 | +++++++++
#15 189.3
#15 189.4 Compiling poly1305 v0.7.2
#15 189.6 Compiling salsa20 v0.9.0
#15 190.3 Compiling pnet_macros_support v0.28.0
#15 190.3 For more information about this error, try `rustc --explain E0310`.
#15 190.3 error: could not compile `rustc-serialize` (lib) due to 1 previous error
#15 190.3 warning: build failed, waiting for other jobs to finish...
#15 ERROR: process "/bin/sh -c cargo build --release --locked" did not complete successfully: exit code: 101
------
> [build 8/10] RUN cargo build --release --locked:
189.3 |
189.3 1151 | impl<'a, T: ?Sized + 'static> Decodable for Cow<'a, T>
189.3 | +++++++++
189.3
189.4 Compiling poly1305 v0.7.2
189.6 Compiling salsa20 v0.9.0
190.3 Compiling pnet_macros_support v0.28.0
190.3 For more information about this error, try `rustc --explain E0310`.
190.3 error: could not compile `rustc-serialize` (lib) due to 1 previous error
190.3 warning: build failed, waiting for other jobs to finish...
------
Dockerfile:15
--------------------
13 | COPY Cargo.toml ./
14 | COPY Cargo.lock ./
15 | >>> RUN cargo build --release --locked
16 |
17 | COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo build --release --locked" did not complete successfully: exit code: 101```

**Comment by SimonStjernholm** [comment]
Btw this happens when trying to build both with amd64 cpu (wsl/ubuntu) and arm cpu (ubuntu server).

**Comment by SimonStjernholm** [comment]
Okay the breaking part here is that the crate `rspotify@v0.11.6` depends on `rustc-serialize`. The crate `rustc-serialize` is now archived/deprecated and when using the latest rust version 1.76.0 (Which Dockerfile uses as image) parrot can't be compiled since of some breaking code changes in this rust version. Compiling with `rpsotify@v0.11.7` works, since it doesn't rely on `rustc-serialize` and also solves spotify-playback (which I couldn't get to work beforehand).

The rust compiler even warns in previous versions, that rustc-serialize will break in future rust versions.
```
The following warnings were discovered during the build. These warnings are an
indication that the packages contain code that will become an error in a
future release of Rust. These warnings typically cover changes to close
soundness problems, unintended or undocumented behavior, or critical problems
that cannot be fixed in a backwards-compatible fashion, and are not expected
to be in wide use.

Each warning should contain a link for more information on what the warning
means and how to resolve it.


To solve this problem, you can try the following approaches:


- If the issue is not solved by updating the dependencies, a fix has to be
implemented by those dependencies. You can help with that by notifying the
maintainers of this problem (e.g. by creating a bug report) or by proposing a
fix to the maintainers (e.g. by creating a pull request):

  - rustc-serialize@0.3.24
  - Repository: https://github.com/rust-lang/rustc-serialize
  - Detailed warning command: `cargo report future-incompatibilities --id 1 --package rustc-serialize@0.3.24`

- If waiting for an upstream fix is not an option, you can use the `[patch]`
section in `Cargo.toml` to use your own version of the dependency. For more
information, see:
https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section
        
The package `rustc-serialize v0.3.24` currently triggers the following future incompatibility lints:
> warning: impl method assumes more implied bounds than the corresponding trait method
>     --> /home/stjernholm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-serialize-0.3.24/src/serialize.rs:1155:41
>      |
> 1155 |     fn decode<D: Decoder>(d: &mut D) -> Result<Cow<'static, T>, D::Error> {
>      |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace this type to make the impl signature compatible: `Result<Cow<'a, T>, <D as serialize::Decoder>::Error>`
>      |
>      = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>      = note: for more information, see issue #105572 <https://github.com/rust-lang/rust/issues/105572>
>      = note: `#[allow(implied_bounds_entailment)]` on by default
>
```

**Comment by SimonStjernholm** [comment]
`rspotify` can also be updated to 0.12.0.
https://github.com/aquelemiguel/parrot/compare/main...SimonStjernholm:parrot:update/rspotify%400.12.0
Only breaking changes for ```rspotify@0.12.0``` in `parrot` should be that a new `market` option parameter is added to the track and album fetcher.
Can add this to this pull as well or submit another one if that's better.

**Comment by joao-conde** [comment]
Sounds ok, fix the clippy lints even though they are unrelated please and we merge it.

**Comment by SimonStjernholm** [comment]
> Sounds ok, fix the clippy lints even though they are unrelated please and we merge it.

It should now be ready for a merge. :)

**Review by joao-conde — APPROVED** [review]

**Comment by joao-conde** [comment]
Thank you for contributing @SimonStjernholm

**Pull request merged**
