### PR TITLE
Feature/14 implement shuffle command

### LINKED ISSUE #14: Implement "shuffle" command
A command that shuffles the current queue.

### Usage
* `!shuffle`

### PR DESCRIPTION
**Pull request by giladwo**
This aims to resolve #14.

### CODE REVIEW

**Comment by aquelemiguel** [comment]
> How do I make sure this works?

Please follow [these steps](https://discordpy.readthedocs.io/en/stable/discord.html) to create a bot account and add it to a server. Then copy its token to a `DISCORD_TOKEN` environment variable and assuming you have FFmpeg and youtube_dl installed, `cargo run` should boot the bot on your server.

BTW, I've tested it on my machine and your code looks great! 👏

**Comment by giladwo** [comment]
> > How do I make sure this works?
> 
> Please check [the updated README](https://github.com/aquelemiguel/parrot/blob/main/README.md) for how to get an instance of Parrot running. slightly_smiling_face
> 
> BTW, I've tested your code on my machine and it looks great! Please just take a look at the requests and I'll be happy to merge it! rocket

Can you be more specific in the README regarding which permissions should be granted to the test bot?
I'm not sure if I'm granting wrong permissions or there's a different issue.

**Comment by giladwo** [comment]
> > Can you be more specific in the README regarding which permissions should be granted to the test bot? I'm not sure if I'm granting wrong permissions or there's a different issue.
> 
> Sure, that's a good addition! In my test server I've given it full admin power, but now retested with more restrictions and these seem to be enough.
> 
> image

That's kinda weird, because I've tried different permissions as well as admin and nothing seems to work.
The bot can join a VC and errors if issued `!play` by a user that's not in a VC (`"Could not find you in any voice channel!"`), but nothing happens if `!play` is issued after entering a VC.
Nothing interesting happens on the shell after `bot is connected!` either.
Any ideas?

**Comment by aquelemiguel** [comment]
> That's kinda weird, because I've tried different permissions as well as admin and nothing seems to work. The bot can join a VC and errors if issued `!play` by a user that's not in a VC (`"Could not find you in any voice channel!"`), but nothing happens if `!play` is issued after entering a VC. Nothing interesting happens on the shell after `bot is connected!` either. Any ideas?

This feels like there's some requirement missing, I've had that happen before.
Can you confirm FFmpeg and youtube-dl are installed? Worst case it's Opus, you might have to install MSVC if on Windows.

**Comment by aquelemiguel** [comment]
> I'm on Fedora 34, got `ffmpeg-libs x64 4.4-6` (from rpmfusion-free-updates) and obviously no MSVC. I guess I need youtube-dl from https://pkgs.org/download/youtube-dl?

Unsure... Songbird (Rust library for Discord's voice API) recommends you install it through pip.
Maybe [this](https://github.com/serenity-rs/songbird#dependencies) can help you get everything set up?

**Comment by giladwo** [comment]
> > I'm on Fedora 34, got `ffmpeg-libs x64 4.4-6` (from rpmfusion-free-updates) and obviously no MSVC. I guess I need youtube-dl from https://pkgs.org/download/youtube-dl?
> 
> Unsure... Songbird (Rust library for Discord's voice API) recommends you install it through pip. Maybe [this](https://github.com/serenity-rs/songbird#dependencies) can help you get everything set up?

Interesting... I do have `opus` - I'll try pip and let you know.

**Pull request merged**
