### PR TITLE
version: 0.4.1

### PR DESCRIPTION
**Pull request by joao-conde**
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | -- |
| Decisions | Bugfixing only, increase `patch` |

### CODE REVIEW

**Comment by joao-conde** [comment]
@afonsojramos  @aquelemiguel  Let's follow this way for new versions, with a PR named `version: major.minor.patch`, a brief decision on what was increased, update `Cargo.toml` and tag this PR as `release`. Finally, once this is merged, do a new tag release.

**Review by afonsojramos — CHANGES_REQUESTED** [review]
This has already been used during testing. The `0.4.X` should be marked as a dead release.

**Comment by afonsojramos** [comment]
Additionally, even though this was a bugfix, you fundamentally changed the way something works, as such, it should not be considered a patch.

**Comment by joao-conde** [comment]
@afonsojramos it is not a new feature for the crate users though.

**Comment by afonsojramos** [comment]
@joao-conde At the moment, versioning is mostly only affecting docker users as we are not publishing the crate anywhere. As such, if `v0.4.x` never worked for docker users, you nuke that minor.

**Comment by afonsojramos** [comment]
In the end, here we are managing the version of two distinct things: The cargo crate and the docker container, and these should be in sync. 

In this case there are "major" (not to confuse with major release) changes to the docker container, as such, we should move on to `v0.5.0`.

**Pull request closed without merging**
