### PR TITLE
feat: add bump action

### PR DESCRIPTION
**Pull request by afonsojramos**
Create an action that updates a Cargo.toml and Cargo.lock so that we don't need to create a branch and make then changes ourselves.

### CODE REVIEW

**Comment by aquelemiguel** [comment]
I'm not too familiar with GitHub Actions, how does this work? How does it know it's supposed to bump to a major/minor/patch and how does it automatically edit the Cargo.toml and Cargo.lock?

**Comment by afonsojramos** [comment]
> How does it know it's supposed to bump to a major/minor/patch
This is an option that will be available in the [actions](https://github.com/aquelemiguel/parrot/actions) page.
```
    inputs:
      version:
        description: 'Version to bump to (e.g. 1.4.3)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
```
> and how does it automatically edit the Cargo.toml and Cargo.lock?

```
      - name: Install cargo-bump
        run: cargo install cargo-bump

      - name: Bump Cargo version
        run: cargo-bump bump ${{ github.event.inputs.version }}

      - name: Bump Cargo.lock
        run: cargo build
```

> I'm not too familiar with GitHub Actions, how does this work?

It does the above then creates a PR using [peter-evans/create-pull-request](https://github.com/marketplace/actions/create-pull-request).

**Comment by aquelemiguel** [comment]
@afonsojramos Okay, thank you for clarifying, let's see it in practice. 🙂

**Review by aquelemiguel — APPROVED** [review]

**Comment by afonsojramos** [comment]
PS: I do not hold responsibility for any damages caused. World may explode 💣

**Pull request merged**
